import Head from 'next/head'
import Navbar from '@/src/components/Navbar'
import Header from '@/src/components/Header'
import Description from '@/src/components/Description'
import Services from '@/src/components/Services'
import Operations from '@/src/components/Operations'
import Footer from '@/src/components/Footer'
import Testimonial from '@/src/components/Testimonial'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='lg:px-5 w-12/12 overflow-hidden 2xl:container 2xl:mx-auto text-white bg-black'>
        <Navbar/>
        <Header/>
        <Description/>
        <Testimonial/>
        <Services/>
        <Operations/>
        <Footer/>
      </main>
    </>
  )
}
